[package]
name = "nbfx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = { version = "7.1.1", default-features = false, features = ["alloc"] }

[dev-dependencies]
hex-literal = "0.3.4"
